// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDviiczyFow2ONUo3qyLkpbUPjtPQOl43s',
    appId: '1:214450735850:android:3d7bf581edc5f7f65ea593',
    messagingSenderId: '214450735850',
    projectId: 'chat--tawat',
    storageBucket: 'chat--tawat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-S503tfaIj2bFU4HN4B7c_4J2TzaMhQ',
    appId: '1:214450735850:ios:b6358cc315ca4c945ea593',
    messagingSenderId: '214450735850',
    projectId: 'chat--tawat',
    storageBucket: 'chat--tawat.appspot.com',
    androidClientId: '214450735850-p5n7449gf2lcbnntta35b9mkmn2gifp2.apps.googleusercontent.com',
    iosClientId: '214450735850-c2tfm3sm5p070gk5dkvr7cmet0ftjn15.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
